portfolio/urls.py
from django.urls import path
from .views import *

app_name = 'portfolio'
urlpatterns = [
    path('', home_page, name='home_page'),
    path('<str:link_name>/', link_view, name='link_view'),
]

portfolio/models.py
from django.db import models
from .utils import SectionItems
import json


class SocialMedia(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.ImageField(max_length=300)
    link = models.CharField(max_length=300)
    alt = models.CharField(max_length=50, default="This")

    def img(self):
        return str(self.image)

    class Meta:
        db_table = "portfolio_social_media"
        verbose_name_plural = "Social Media"

    def __str__(self):
        return self.alt

    @property
    def image_url(self):
        return "portfolio/img/{}".format(self.image.url)


class Section(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    layout = models.ForeignKey('Layout', on_delete=models.SET_NULL, null=True)
    data = models.TextField(default="{}")
    styles = models.TextField(default='{"style":[]}')
    menu = models.BooleanField(default=True)
    home = models.BooleanField(default=True)
    link = models.CharField(max_length=100, default="#")
    order = models.IntegerField(default=0)

    # data keys refer to hard coded names in layout
    # data values refer to textbody or imagefile ids
    # data structure depends on layout.data

    class Meta:
        db_table = "portfolio_section"
        verbose_name = "Section"

    def __str__(self):
        return self.name

    @property
    def get_link(self):
        if self.home and self.menu and self.link == "#":
            self.link = "#{}".format(self.name)
            self.save()
        return self.link

    @property
    def get_styles(self):
        styles = json.loads(self.styles)
        return " ".join(styles.get("style"))

    def set_data_keys(self):
        if self.layout:
            self.data = self.layout.get_data()
            self.save()
            return True
        return False

    def get_data(self):
        for i, j in json.loads(self.data).items():

            if 'img' in i and j != "":
                item = ImageFile.objects.filter(id=int(j)).first()
            elif 'text' in i and j != "":
                item = TextBody.objects.filter(id=int(j)).first()
            elif 'link' in i and j != "":
                item = Page.objects.filter(id=int(j)).first()
            else:
                item = None
            setattr(self, i, item)

    @property
    def view_all(self):
        show_view_all = False
        for i, j in json.loads(self.data).items():
            attr_name, attr_num = i.split("_")
            if int(attr_num) == 3:
                show_view_all = True
                break
        return show_view_all

    @property
    def items(self):
        count = 1
        attr_temp = {}
        attr_list = []
        for i, j in json.loads(self.data).items():
            attr_name, attr_num = i.split("_")

            if count == 4:
                break

            if int(attr_num) != count:
                attr_list.append(SectionItems(img=attr_temp.get('img'),
                                              text=attr_temp.get('text'),
                                              link=attr_temp.get('link')))
                attr_temp = dict()
                count += 1

            if 'img' in attr_name and j != "":
                item = ImageFile.objects.filter(id=int(j)).first()
                attr_temp[attr_name] = item
            elif 'text' in attr_name and j != "":
                item = TextBody.objects.filter(id=int(j)).first()
                attr_temp[attr_name] = item
            elif 'link' in attr_name and j != "":
                item = Page.objects.filter(id=int(j)).first()
                attr_temp[attr_name] = item

        if attr_temp:
            attr_list.append(SectionItems(img=attr_temp.get('img'),
                                          text=attr_temp.get('text'),
                                          link=attr_temp.get('link')))
        return attr_list


class TextBody(models.Model):
    id = models.AutoField(primary_key=True)
    text = models.TextField()
    section = models.ForeignKey('Section', on_delete=models.CASCADE)

    class Meta:
        db_table = "portfolio_text_body"
        verbose_name = "Text Body"

    def __str__(self):
        return self.text


class ImageFile(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.ImageField(max_length=300)
    image_resize = models.ImageField(max_length=300, default=None, null=True, blank=True)
    section = models.ForeignKey('Section', on_delete=models.CASCADE)

    class Meta:
        db_table = "portfolio_image_file"
        verbose_name = "Image File"

    def __str__(self):
        return str(self.image)

    @property
    def image_url(self):
        return "portfolio/img/{}".format(self.image.url)


class Layout(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default="", max_length=100)
    template = models.CharField(max_length=1000)
    data = models.TextField(default="")

    class Meta:
        db_table = "portfolio_layout"
        verbose_name = "Layout"

    # Data is a dict that controls where the images and texts belong
    # depending on the layout, the data will be organized differently
    # users will fill out the data dict to organize the content in the layout

    # the keys of the data determine the position of text/images in the layout
    # the values will be determined by the user

    # eventually the user will be able to create the layout and set the keys
    def __str__(self):
        return self.name

    def set_data(self, data):
        self.data = json.dumps(data)
        self.save()
        return True

    def get_data(self):
        return json.loads(self.data)


class Page(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=50)
    data = models.TextField(default="{}")
    layout = models.ForeignKey('Layout', on_delete=models.SET_NULL, null=True, default=None)

    class Meta:
        db_table = "portfolio_page"
        verbose_name = "Page"

    def __str__(self):
        return self.name

    @staticmethod
    def url_to_name(url_name):
        return " ".join(url_name.split("-"))

    @property
    def name_url(self):
        return "-".join(self.name.split(" "))

    def set_data_keys(self):
        if self.layout:
            self.data = self.layout.get_data()
            self.save()
            return True
        return False

    def get_data(self):
        for i, j in json.loads(self.data).items():

            if 'img' in i and j != "":
                item = ImageFile.objects.filter(id=int(j)).first()
            elif 'text' in i and j != "":
                item = TextBody.objects.filter(id=int(j)).first()
            elif 'link' in i and j != "":
                item = Page.objects.filter(id=int(j)).first()
            else:
                item = None
            setattr(self, i, item)

portfolio/views.py
from django.shortcuts import render
from .models import *
from .constants import Constant


def home_page(request):
    all_sections = Section.objects.all().order_by("order")
    sections = all_sections.filter(home=True)
    menu = all_sections.filter(menu=True)

    social_media = SocialMedia.objects.all()
    for section in sections:
        section.get_data()

    context = {
        "title": Constant.CONSTANT_TITLE,
        "sections": sections,
        'menu': menu,
        "social_media": social_media,
    }
    template = "portfolio/home_page.html"

    return render(request, template, context)


def link_view(request, link_name):
    page = Page.objects.filter(name=Page.url_to_name(link_name)).first()
    if page:
        page.get_data()
    context = {"title": Constant.CONSTANT_TITLE,
               'page': page}
    template = "portfolio/page.html"
    return render(request, template, context)


def handler_error(request):
    return render(request, 'portfolio/error.html')

portfolio/templates/layout/layout_eight.html
{% load static %}
<div class="bg-dark vh-25 vw-100"
     style="background-image: url({% static "/portfolio/img/andrew-stutesman-l68Z6eF2peA-unsplash.jpg" %});
             background-size: cover;
             background-position: center;">
    <div class="h-100 w-100 tinted-center">
        <div class="text-theme-secondary m-auto font-kingsbridge font-weight-bold">
            <div class="d-flex">
                <img class="d-none d-sm-flex" style="max-width: 100px;"
                     src="{% static page.img_5.image_url %}" alt="{{ page.text_5.text }}">
                <h1>{{ page.name }}</h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="jumbotron">
        <div class="row font-kingsbridge">
            <div class="col">
                <div class="font-weight-bold pl-2">
                    summary &#x2501;
                </div>
            </div>
        </div>
        <div class="row font-oswald">
            <div class="col-10 col-md-6 offset-1 offset-md-3">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate quis leo non finibus.
                Suspendisse lorem ipsum, vehicula ut tempus vel, hendrerit aliquet mi. Maecenas molestie nunc eu
                fermentum hendrerit. Maecenas sit amet condimentum arcu. Integer fermentum sapien eu blandit volutpat.
                Duis sit amet est sed massa dignissim vulputate sed a diam. Etiam vitae mattis dolor. Duis non luctus
                orci, sed pulvinar velit. Cras egestas lectus in tellus tempor, at pulvinar ex faucibus. Vestibulum
                accumsan tortor et gravida facilisis. In volutpat nec nisl et cursus.
            </div>
        </div>
        <hr>
        <div class="row font-kingsbridge">
            <div class="col">
                <div class="font-weight-bold">
                    visit &#x2501;
                </div>
                <div class="text-dark font-oswald text-center">
                    <a href="http://www.bwanaz.com" class="btn bg-theme-accent-light">Github</a>
                </div>
            </div>
            <div class="col">
                <div class="font-weight-bold">
                    roles &#x2501;
                </div>
                <div class="font-oswald">
                    <div class="text-dark text-center">
                        Software Engineer
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="font-weight-bold">
                    timeline &#x2501;
                </div>
                <div class="text-dark font-oswald text-center">
                    June 2020 - July 2020
                </div>
            </div>
        </div>
        <hr>
        <div class="row font-kingsbridge">
            <div class="col">
                <div class="font-weight-bold pl-2">
                    skills &#x2501;
                </div>
            </div>
            <div class="container text-center">
                <div class="row d-flex">
                    <div class="col-3 my-auto slide-left dur-1 m-auto">
                        <img class="w-100" src="{% static page.img_1.image_url %}" alt="{{ page.text_1.text }}">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row py-3 bg-theme-primary">
        <div class="col">
            <div class="font-kingsbridge font-weight-bold">
                <h1>00. DEEP DIVE &#8628;</h1>
            </div>
        </div>
    </div>
    <br>
    <div class="row" id="tab-1">
        <div class="col offset-2">
            <div class="font-kingsbridge font-weight-bold">
                <h3><span class="bg-theme-primary p-1 rounded">01.</span> Lorem Ipsum &#x2501;</h3>
            </div>
        </div>
        <div class="col-12 font-oswald">
            <div class="row">
                <div class="col-12 col-md-6 d-flex">
                    <img class="mx-auto"
                         style="max-width: 100% "
                         src="{% static "" %}"
                         alt="">
                </div>
                <div class="col-12 col-md-6 d-flex">
                    <div class="m-auto">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate quis leo non
                            finibus. Suspendisse lorem ipsum, vehicula ut tempus vel, hendrerit aliquet mi. Maecenas
                            molestie nunc eu fermentum hendrerit. Maecenas sit amet condimentum arcu. Integer fermentum
                            sapien eu blandit volutpat. Duis sit amet est sed massa dignissim vulputate sed a diam.
                            Etiam vitae mattis dolor. Duis non luctus orci, sed pulvinar velit. Cras egestas lectus in
                            tellus tempor, at pulvinar ex faucibus. Vestibulum accumsan tortor et gravida facilisis. In
                            volutpat nec nisl et cursus.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row" id="tab-2">
        <div class="col offset-2 d-inline d-md-none">
            <div class="font-kingsbridge font-weight-bold">
                <h3><span class="bg-theme-primary p-1 rounded">02.</span> Lorem Ipsum &#x2501;</h3>
            </div>
        </div>
        <div class="col-12 bg-light font-oswald p-3">
            <div class="row">
                <div class="col d-flex">
                    <div class="m-auto">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate quis leo non
                            finibus. Suspendisse lorem ipsum, vehicula ut tempus vel, hendrerit aliquet mi. Maecenas
                            molestie nunc eu fermentum hendrerit. Maecenas sit amet condimentum arcu. Integer fermentum
                            sapien eu blandit volutpat. Duis sit amet est sed massa dignissim vulputate sed a diam.
                            Etiam vitae mattis dolor. Duis non luctus orci, sed pulvinar velit. Cras egestas lectus in
                            tellus tempor, at pulvinar ex faucibus. Vestibulum accumsan tortor et gravida facilisis. In
                            volutpat nec nisl et cursus.</p>
                    </div>
                </div>
                <div class="col d-none d-md-flex">
                    <div class="font-kingsbridge font-weight-bold m-auto">
                        <h3>&#x2501; <span class="bg-theme-primary p-1 rounded">02.</span> Lorem Ipsum </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row" id="tab-3">
        <div class="col offset-2">
            <div class="font-kingsbridge font-weight-bold">
                <h3><span class="bg-theme-primary p-1 rounded">03.</span> Lorem Ipsum &#x2501;</h3>
            </div>
        </div>
        <div class="col-12 font-oswald p-3">
            <div class="row">
                <div class="col d-flex">
                    <div class="m-auto">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate quis leo non
                            finibus. Suspendisse lorem ipsum, vehicula ut tempus vel, hendrerit aliquet mi. Maecenas
                            molestie nunc eu fermentum hendrerit. Maecenas sit amet condimentum arcu. Integer fermentum
                            sapien eu blandit volutpat. Duis sit amet est sed massa dignissim vulputate sed a diam.
                            Etiam vitae mattis dolor. Duis non luctus orci, sed pulvinar velit. Cras egestas lectus in
                            tellus tempor, at pulvinar ex faucibus. Vestibulum accumsan tortor et gravida facilisis. In
                            volutpat nec nisl et cursus.</p>
                    </div>
                </div>
                <div class="col-12 col-md-6 d-flex">
                    <img class="mx-auto"
                         style="max-width: 100% "
                         src="{% static "" %}"
                         alt="">
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row" id="tab-4">
        <div class="col offset-2 d-inline d-md-none">
            <div class="font-kingsbridge font-weight-bold">
                <h3><span class="bg-theme-primary p-1 rounded">04.</span> Lorem Ipsum &#x2501;</h3>
            </div>
        </div>
        <div class="col-12 bg-light font-oswald p-3">
            <div class="row">
                <div class="col d-none d-md-flex">
                    <div class="font-kingsbridge font-weight-bold m-auto">
                        <h3><span class="bg-theme-primary p-1 rounded">04.</span> Lorem Ipsum &#x2501;</h3>
                    </div>
                </div>
                <div class="col d-flex">
                    <div class="m-auto">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate quis leo non
                            finibus. Suspendisse lorem ipsum, vehicula ut tempus vel, hendrerit aliquet mi. Maecenas
                            molestie nunc eu fermentum hendrerit. Maecenas sit amet condimentum arcu. Integer fermentum
                            sapien eu blandit volutpat. Duis sit amet est sed massa dignissim vulputate sed a diam.
                            Etiam vitae mattis dolor. Duis non luctus orci, sed pulvinar velit. Cras egestas lectus in
                            tellus tempor, at pulvinar ex faucibus. Vestibulum accumsan tortor et gravida facilisis. In
                            volutpat nec nisl et cursus.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row" id="tab-5">
        <div class="col offset-2 d-inline d-md-none">
            <div class="font-kingsbridge font-weight-bold">
                <h3><span class="bg-theme-primary p-1 rounded">05.</span> Lorem Ipsum &#x2501;</h3>
            </div>
        </div>
        <div class="col-12 font-oswald p-3">
            <div class="row">
                <div class="col d-flex">
                    <div class="m-auto">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vulputate quis leo non
                            finibus. Suspendisse lorem ipsum, vehicula ut tempus vel, hendrerit aliquet mi. Maecenas
                            molestie nunc eu fermentum hendrerit. Maecenas sit amet condimentum arcu. Integer fermentum
                            sapien eu blandit volutpat. Duis sit amet est sed massa dignissim vulputate sed a diam.
                            Etiam vitae mattis dolor. Duis non luctus orci, sed pulvinar velit. Cras egestas lectus in
                            tellus tempor, at pulvinar ex faucibus. Vestibulum accumsan tortor et gravida facilisis. In
                            volutpat nec nisl et cursus.</p>
                    </div>
                </div>
                <div class="col d-none d-md-flex">
                    <div class="font-kingsbridge font-weight-bold m-auto">
                        <h3>&#x2501; <span class="bg-theme-primary p-1 rounded">05.</span> Lorem Ipsum</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
</div>

portfolio/templates/layout/layout_four.html
{% load static %}
<div class="section-content">
    <div class="section-body">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6 offset-lg-3 bg-theme-primary border-thick border-dark mt-5">
                    <img class="w-100" src="{% static section.img_1.image_url %}" alt="img-one">
                    <div class="img-text text-nowrap">
                        <div class="row">
                            <div class="col-12">
                                <span class="font-kingsbridge img-font-size text-white font-weight-bold">
                                    {{ section.text_1.text|linebreaksbr }}
                                </span>
                            </div>
                            <div class="col-12 bg-transparent-light">
                                <span class="font-oswald img-font-size-sm text-white">
                                    {{ section.text_2.text|linebreaksbr }}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

portfolio/templates/layout/layout_one.html
{% load static %}
<div class="section-content mt-5">
    <div class="section-body w-100">
        <div class="container container-width mx-auto">
            <div class="row">
                <div class="col section-title text-center font-kingsbridge font-weight-bold font-size-2rem">
                    <span class="bg-theme-secondary px-4">{{ section.name }}</span>
                </div>
            </div>
            <div class="row my-2 p-2 h-100">
                {% for item in section.items %}
                    <div class="col-3 p-0 p-sm-1">
                        <img class="w-100" src="{% static item.img.image_url %}" alt="img-one">
                    </div>
                    <div class="col-9 my-auto">
                        <div class="row">
                            <div class="col text-center font-oswald">
                                <a href="{% url 'portfolio:link_view' item.link.name_url %}">
                                    <h2 class="project-link link-hover">{{ item.text.text|linebreaksbr }}</h2>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

portfolio/templates/layout/layout_six.html
{% load static %}
<div class="vh-100 d-flex">
    <div class="container m-auto">
        <div class="row">
            <div class="col-12 col-md d-flex p-0 vh-50"
                 style="background-image: url({% static "/portfolio/img/baby_picture.jpg" %});
                         background-size: cover;
                         background-position: center;">
                <div class="h-100 w-100 tinted-center">
                    <div class="m-auto font-kingsbridge font-weight-bold text-center text-theme-secondary font-size-4rem">
                        {{ page.name }}
                    </div>
                </div>
            </div>
            <div class="col-12 col-md d-flex bg-light">
                <div class="p-4 font-kingsbridge m-auto">
                    <p>Justin Shan Chun Fu is a Python Software Engineer based in California. He has a B.S. in Computer
                        Science from UC Irvine. Justin is currently a Full Stack Django developer with an interest in
                        web dev and machine learning.</p>
                    <div class="d-flex">
                        <div class="m-auto">
                            <p>Watch &#x2501;
                                <a href="https://www.youtube.com/watch?v=1-TWkrDbYjs&ab_channel=VIBRVNCY"> Justin
                                    dance</a>
                            </p>
                            <p>Play &#x2501;
                                <a href="https://na.op.gg/summoner/userName=Aktahphoo">League of Legends</a>
                            </p>
                            <p>Play &#x2501;
                                <a href="https://playoverwatch.com/en-us/career/pc/yoriik-11662/">Overwatch</a>
                            </p>
                            <p>Current &#x2501;
                                <a href="https://open.spotify.com/playlist/5EBrBseVW4vJpBiaKEh0wx?si=cq6OmSgFQ4ibo-l-PBEWHg">playlist</a>
                            </p>
                            <p>Contact &#x2501;
                                <a href="mailto:fu.justin.s@gmail.com">Email</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

portfolio/templates/layout/layout_three.html
{% load static %}
<div class="section-content">
    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <li class="list-group-item border-0 bg-theme-secondary text-center">
                    <div class="row">
                        {% for social in social_media %}
                            <div class="col">
                                <a href="{{ social.link }}">
                                    <img src="{% static social.image_url %}" alt="{{ social.alt }}"
                                         class="img-medium link-hover">
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </li>
            </div>
        </div>
    </div>
</div>

portfolio/templates/layout/layout_two.html
<div class="section-content">
    <div class="section-body">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <div class="font-oswald banner-text bg-text-image">
                        <div class="text-transparent transform-transparent bg-theme-secondary py-1">
                            {{ section.text_1.text }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <div class="font-oswald banner-text bg-text-image">
                        <div class="text-transparent transform-transparent bg-theme-secondary py-1">
                            {{ section.text_2.text }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

portfolio/templates/portfolio/error.html
{% extends 'portfolio/base.html' %}
{% block title %}
    Something went wrong.
{% endblock %}
{% block header %}
    {% include "portfolio/header_2.html" %}
{% endblock %}
{% block body %}
    <div class="container vh-90  d-flex">
        <div class="m-auto font-kingsbridge">
            <div class="bg-light p-3">
                <h1><span class="error-page error-anim-1">Yikes</span></h1>
                <h4>
                    <span class="error-page error-anim-2">That's</span>
                    <span class="error-page error-anim-3">embarassing.</span>
                </h4>
                <h1><span class="error-page error-anim-4">Something</span></h1>
                <h2>
                    <span class="error-page error-anim-5">went</span>
                    <span class="error-page error-anim-6">wrong.</span>
                </h2>
            </div>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/footer.html
<footer class="footer mt-auto">
    <div class="nav bg-theme-secondary h-100">
        <div class="container">
            <div class="row py-3 my-3">
                <div class="col-12 text-center text-theme-accent-dark font-kingsbridge font-size-40">
                    <a href="{% url 'portfolio:home_page' %}"
                    class="link-hover">
                        SHAN CHUN
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

portfolio/templates/portfolio/header.html
{% load static %}
<header>
    <nav class="navbar fixed-top bg-transparent">
        <a class="navbar-brand pl-1 font-kingsbridge link-hover" href="{% url "portfolio:home_page" %}">SHAN CHUN</a>
        <button class="navbar-toggler collapsed link-hover" type="button" data-toggle="modal"
                data-target="#nav-modal" aria-expanded="false">
            <img class="menu-icon-size" src="{% static "portfolio/img/menu-512x512.png" %}" alt="menu">
        </button>
    </nav>

    <!-- Modal -->
    <div class="modal fade bg-theme-secondary" id="nav-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         data-backdrop="false">
        <button type="button"
                class="modal-close close text-theme-accent-dark font-size-40 link-hover top-right"
                data-dismiss="modal"
                aria-label="Close">
            <span aria-hidden="true">
                <img class="navbar-exit link-hover"
                     style="height: 50px"
                     src="{% static 'portfolio/img/iconfinder_close_512x512.png' %}"
                     alt="back">
            </span>
        </button>
        <div class="modal-dialog modal-dialog-centered modal-sm bg-theme-secondary" role="document">
            <div class="modal-content border-0 bg-theme-secondary">
                <div class="modal-body" id="nav-modal-menu">
                    <ul class="list-group">
                        <!-- Menu Item -->
                        {% for section in menu %}
                            <li class="list-group-item border-0 bg-theme-secondary">
                                <h1 class="col-12 menu-modal-link p-1 text-center link-hover">
                                    <a href="{{ section.get_link }}"
                                            {% if section.name == "RESUME" %}
                                       target="_blank"
                                            {% endif %}>{{ section.name }}</a>
                                </h1>
                            </li>
                        {% endfor %}

                        <!-- Social Media -->
                        <li class="list-group-item border-0 bg-theme-secondary text-center">
                            <div class="row">
                                {% for social in social_media %}
                                    <div class="col">
                                        <a href="{{ social.link }}">
                                            <img src="{% static social.image_url %}" alt="{{ social.alt }}"
                                                 class="img-icon link-hover">
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

portfolio/templates/portfolio/header_2.html
{% load static %}
<nav class="navbar fixed-top bg-transparent">
    <a class="navbar-brand pl-1 font-oswald link-hover" href="{% url "portfolio:home_page" %}">SHAN CHUN</a>
    <a href="{% url 'portfolio:home_page' %}">
        <img class="navbar-exit project-link link-hover"
             style="height: 50px"
             src="{% static 'portfolio/img/iconfinder_close_512x512.png' %}"
             alt="back">
    </a>
</nav>

portfolio/templates/portfolio/page.html
{% extends "portfolio/base.html" %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block header %}
    {% include 'portfolio/header_2.html' %}
{% endblock %}
{% block body %}
    <div class="page-loader bg-theme-accent-dark">
        <div class="text-center m-auto font-size-5rem loading"></div>
    </div>
    {% include page.layout.template %}
{% endblock %}
{% block footer %}
{% endblock %}
{% block js_scripts %}
    <script src="{% static "portfolio/js/pageLoader.js" %}"></script>
{% endblock %}